// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class BuyjoelofferTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void buyjoeloffer() {
    driver.Navigate().GoToUrl("https://live.joelosteen.com/offer");
    driver.FindElement(By.Id("gifts")).Click();
    {
      var dropdown = driver.FindElement(By.Id("gifts"));
      dropdown.FindElement(By.XPath("//option[. = 'BELIEVE']")).Click();
    }
    driver.FindElement(By.CssSelector(".form-row:nth-child(3) .form-check-label")).Click();
    driver.FindElement(By.CssSelector(".form-row:nth-child(3) .form-check-label")).Click();
    driver.FindElement(By.Id("amount")).Click();
    {
      var dropdown = driver.FindElement(By.Id("amount"));
      dropdown.FindElement(By.XPath("//option[. = '250']")).Click();
    }
    driver.FindElement(By.Id("submit-aco-form")).Click();
    driver.FindElement(By.Id("checkout-username")).Click();
    driver.FindElement(By.Id("checkout-username")).SendKeys("jeremyjr+tester@lakey.net");
    driver.FindElement(By.Id("checkout-submit-username-form")).Click();
    driver.FindElement(By.Id("checkout-password")).Click();
    driver.FindElement(By.Id("checkout-password")).SendKeys("TryThis#1");
    {
      var element = driver.FindElement(By.Id("checkout-submit-signin-form"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    driver.FindElement(By.Id("checkout-submit-signin-form")).Click();
    driver.FindElement(By.Id("checkout-cardnumber")).Click();
    driver.FindElement(By.Id("checkout-cardnumber")).SendKeys("5454545454545454");
    driver.FindElement(By.Id("checkout-cardexp")).SendKeys("1234");
    driver.FindElement(By.Id("checkout-cardcvv")).SendKeys("123");
    driver.FindElement(By.Id("checkout-submit-payment-detail-form")).Click();
    driver.FindElement(By.CssSelector("#checkout-submit-review-form > span")).Click();
  }
}
