// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class LivelakewooddonatewithaccTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void livelakewooddonatewithacc() {
    driver.Navigate().GoToUrl("https://live.lakewoodchurch.com/");
    driver.Manage().Window.Size = new System.Drawing.Size(945, 1020);
    driver.FindElement(By.CssSelector(".navbar-toggler-icon")).Click();
    driver.FindElement(By.CssSelector(".nav-link:nth-child(10)")).Click();
    driver.FindElement(By.Id("giveform-donationamount")).Click();
    driver.FindElement(By.Id("giveform-donationamount")).SendKeys("50");
    driver.FindElement(By.Id("giveform-submit-donation-form")).Click();
    driver.FindElement(By.Id("giveform-username")).Click();
    driver.FindElement(By.Id("giveform-username")).SendKeys("jeremyjr+tester@lakey.net");
    driver.FindElement(By.Id("giveform-username")).SendKeys(Keys.Enter);
    driver.FindElement(By.Id("giveform-password")).SendKeys("TryThis#1");
    driver.FindElement(By.Id("giveform-submit-signin-form")).Click();
    driver.FindElement(By.CssSelector("#giveform-review-form #giveform-paymentmethod")).Click();
    {
      var dropdown = driver.FindElement(By.CssSelector("#giveform-review-form #giveform-paymentmethod"));
      dropdown.FindElement(By.XPath("//option[. = 'New Payment Method']")).Click();
    }
    driver.FindElement(By.Id("giveform-submit-review-form")).Click();
    driver.FindElement(By.CssSelector("#giveform-review-form .mt-3")).Click();
    driver.FindElement(By.Id("giveform-submit-donation-form")).Click();
    js.ExecuteScript("window.scrollTo(0,976)");
    driver.FindElement(By.Id("giveform-submit-payment-form")).Click();
    driver.FindElement(By.Id("giveform-cardnumber")).SendKeys("5454545454545454");
    driver.FindElement(By.CssSelector("#giveform-payment-detail-form .col-md-9")).Click();
    driver.FindElement(By.Id("giveform-cardexp")).Click();
    driver.FindElement(By.Id("giveform-cardexp")).SendKeys("1234");
    driver.FindElement(By.CssSelector("#giveform-payment-detail-form .col-md-9")).Click();
    driver.FindElement(By.Id("giveform-cardcvv")).Click();
    driver.FindElement(By.Id("giveform-cardcvv")).SendKeys("123");
    driver.FindElement(By.CssSelector(".p-3:nth-child(2)")).Click();
    driver.FindElement(By.Id("giveform-submit-payment-detail-form")).Click();
    driver.FindElement(By.Id("giveform-submit-review-form")).Click();
    driver.FindElement(By.CssSelector("#giveform #giveform-logout-button")).Click();
  }
}
