// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;

[TestFixture]
public class LivejoelaccmakerTest
{
    private IWebDriver driver;
    public IDictionary<string, object> vars { get; private set; }
    private IJavaScriptExecutor js;

    [SetUp]
    public void SetUp()
    {
        driver = new ChromeDriver();
        js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<string, object>();
    }

    [TearDown]
    protected void TearDown()
    {
        driver.Quit();
    }

    [Test]
    public void livejoelaccmaker()
    {
        driver.Navigate().GoToUrl("https://live.joelosteen.com/");
        driver.Manage().Window.Size = new System.Drawing.Size(945, 1020);
        Thread.Sleep(5000); // 5 second delay
        driver.FindElement(By.Id("popup-signin-signin")).Click();
        
        // Delay for 2 seconds
        Thread.Sleep(2000);
        
        driver.FindElement(By.Id("popup-signin-email-1")).Click();
        driver.FindElement(By.Id("popup-signin-show-create-account-form")).Click();
        
        // Delay for 2 seconds
        Thread.Sleep(2000);
        
        driver.FindElement(By.Id("popup-signin-firstname")).SendKeys("Jeremy");
        driver.FindElement(By.Id("popup-signin-lastname")).SendKeys("Lakey");

        // Generate dynamic email based on current time and date
        string timestamp = DateTime.Now.ToString("yyyyMMddHHmmss");
        string email = $"jeremyjr+{timestamp}@lakey.net";
        driver.FindElement(By.Id("popup-signin-email-3")).SendKeys(email);

        driver.FindElement(By.Id("popup-signin-postalcode")).Click();
        driver.FindElement(By.Id("popup-signin-postalcode")).SendKeys("74055");
        driver.FindElement(By.CssSelector(".form-row:nth-child(8) .mr-5 span:nth-child(1)")).Click();
        driver.FindElement(By.Id("popup-signin-agreeterms-1")).Click();
        
        // Delay for 2 seconds
        Thread.Sleep(2000);

        driver.FindElement(By.Id("popup-signin-submit-create-account-form")).Click();
        Thread.Sleep(8000);
    }
}
